# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Harshith
  demands:
  - Agent.Name -equals Harshithb

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js 14'

- script: |
    cd backend
    npm install
  displayName: 'Install npm dependencies'

- script: |
    cd backend
    npm test
  displayName: 'Run tests'
  continueOnError: true

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQube1'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'online_store_mern'
    cliProjectName: 'online_store_mern'
    cliSources: 'backend'
  displayName: 'Prepare SonarQube Analysis'

- task: SonarQubeAnalyze@5
  displayName: 'Run SonarQube Analysis'

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish SonarQube Results'